### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by hzhao1997** [tmanh/view_synthesis_methods#1]
Thanks for your contribution, could you offer some data of this code?

**Comment by tmanh** [comment]
Hi,

First, I have not completed the code yet.

For dataset, I guess you can try to access Scannet dataset, it is a 3D reconstruction dataset. But, they provided the camera calibration for every single frame. So, you can test the view synthesis code on that dataset. You just need to fill in a form before downloading that dataset.

Best regards,
Anh Minh Truong.

**Comment by hzhao1997** [comment]
ok, I will try it. Thank you~
